# Generated by Django 6.0.6 on 2026-06-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnamSaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Onam Saree',
                'verbose_name_plural': 'Onam Sarees',
                'db_table': 'onam_sarees',
            },
        ),
        migrations.CreateModel(
            name='OnamSareeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='onam_sarees/')),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.onamsaree')),
            ],
        ),
    ]
