# Generated by Django on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnamSetMund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Onam Set-Mund',
                'verbose_name_plural': 'Onam Set-Munds',
                'db_table': 'onam_munds',
            },
        ),
        migrations.CreateModel(
            name='OnamSetMundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='onam_munds/')),
                ('mund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.onamsetmund')),
            ],
            options={
                'db_table': 'product_onammundimage',
            },
        ),
    ]
