# Generated by Django 6.0.6 on 2026-06-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_create_onam_mund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onamsetmundimage',
            options={'verbose_name': 'Onam Set-Mund Image', 'verbose_name_plural': 'Onam Set-Mund Images'},
        ),
        migrations.AddField(
            model_name='onamsaree',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onamsaree',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onamsetmund',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onamsetmund',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onamsetmundimage',
            name='mund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.onamsetmund'),
        ),
    ]
