# Generated by Django 6.0.6 on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_onamsetmundimage_options_onamsaree_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredSaree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colored Saree',
                'verbose_name_plural': 'Colored Sarees',
                'db_table': 'colored_sarees',
            },
        ),
        migrations.CreateModel(
            name='ColoredSareeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colored_sarees/')),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.coloredsaree')),
            ],
        ),
    ]
