# Generated by Django 6.0.6 on 2026-07-25 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_create_colored_saree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloredsareeimage',
            options={'verbose_name': 'Colored Saree Image', 'verbose_name_plural': 'Colored Saree Images'},
        ),
        migrations.AlterField(
            model_name='coloredsareeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='onamsareeimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='onamsetmundimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
