# Generated by Django 6.0.6 on 2026-07-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_coloredsareeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coloredsaree',
            options={'verbose_name': 'MOST PURCHASED SAREE', 'verbose_name_plural': 'MOST PURCHASED SAREES'},
        ),
        migrations.AlterModelOptions(
            name='onamsaree',
            options={'verbose_name': 'FEATURED ONAM', 'verbose_name_plural': 'FEATURED ONAM'},
        ),
        migrations.AlterModelOptions(
            name='onamsetmund',
            options={'verbose_name': 'SHOP BY COLLECTION', 'verbose_name_plural': 'SHOP BY COLLECTION'},
        ),
        migrations.AlterModelTable(
            name='coloredsaree',
            table='most_purchased_sarees',
        ),
        migrations.AlterModelTable(
            name='onamsaree',
            table='featured_onam',
        ),
        migrations.AlterModelTable(
            name='onamsetmund',
            table='shop_by_collection',
        ),
    ]
