# Generated by Django 6.0.6 on 2026-07-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_coloredsaree_options_alter_onamsaree_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onamsaree',
            options={'verbose_name': 'FEATURED ONAM PICKS', 'verbose_name_plural': 'FEATURED ONAM PICKS'},
        ),
        migrations.AlterModelTable(
            name='onamsaree',
            table='featured_onam_picks',
        ),
    ]
