# Generated by Django 6.0.6 on 2026-07-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_onamsaree_options_alter_onamsaree_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onamsaree',
            options={'verbose_name': 'FEATURED ONAM PICKS PICKS', 'verbose_name_plural': 'FEATURED ONAM PICKS PICKS'},
        ),
    ]
