# Generated by Django 6.0.6 on 2026-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
