# Generated by Django 6.0.6 on 2026-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_siteuser_raw_password_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
