# Generated by Django 6.0.6 on 2026-08-02 05:52

from django.db import migrations

def merge_products(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    ProductImage = apps.get_model('product', 'ProductImage')
    
    OnamSaree = apps.get_model('product', 'OnamSaree')
    OnamSetMund = apps.get_model('product', 'OnamSetMund')
    ColoredSaree = apps.get_model('product', 'ColoredSaree')
    
    # 1. OnamSaree
    for item in OnamSaree.objects.all():
        product = Product.objects.create(
            category='featured_onam_picks',
            collection_name=item.collection_name,
            description=item.description,
            price=item.price,
            quantity=item.quantity,
            stock_available=item.stock_available
        )
        for img in item.images.all():
            ProductImage.objects.create(product=product, image=img.image)
            
    # 2. OnamSetMund
    for item in OnamSetMund.objects.all():
        product = Product.objects.create(
            category='shop_by_collection',
            collection_name=item.collection_name,
            description=item.description,
            price=item.price,
            quantity=item.quantity,
            stock_available=item.stock_available
        )
        for img in item.images.all():
            ProductImage.objects.create(product=product, image=img.image)
            
    # 3. ColoredSaree
    for item in ColoredSaree.objects.all():
        product = Product.objects.create(
            category='most_purchased_sarees',
            collection_name=item.collection_name,
            description=item.description,
            price=item.price,
            quantity=item.quantity,
            stock_available=item.stock_available
        )
        for img in item.images.all():
            ProductImage.objects.create(product=product, image=img.image)

def reverse_merge(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_productimage'),
    ]

    operations = [
        migrations.RunPython(merge_products, reverse_merge),
    ]
