# Generated by Django 6.0.6 on 2026-08-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20260802_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloredsareeimage',
            name='saree',
        ),
        migrations.RemoveField(
            model_name='onamsareeimage',
            name='saree',
        ),
        migrations.RemoveField(
            model_name='onamsetmundimage',
            name='mund',
        ),
        migrations.DeleteModel(
            name='ColoredSaree',
        ),
        migrations.DeleteModel(
            name='ColoredSareeImage',
        ),
        migrations.DeleteModel(
            name='OnamSaree',
        ),
        migrations.DeleteModel(
            name='OnamSareeImage',
        ),
        migrations.DeleteModel(
            name='OnamSetMund',
        ),
        migrations.DeleteModel(
            name='OnamSetMundImage',
        ),
    ]
