# Generated by Django 6.0.6 on 2026-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_updationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_type',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='updationtask',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='updationtask',
            name='purchase_type',
            field=models.CharField(default='Online', max_length=50),
        ),
    ]
