# Generated by Django 6.0.6 on 2026-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_order_payment_type_order_purchase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_collection_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_collection_table',
            field=models.BooleanField(default=False),
        ),
    ]
