# Generated by Django 6.0.6 on 2026-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_category_show_in_collection_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('coupon_name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Coupon',
                'verbose_name_plural': 'Product Coupons',
                'db_table': 'product_coupon',
                'ordering': ['-created_at'],
            },
        ),
    ]
