# Generated by Django 6.0.6 on 2026-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoupon',
            name='min_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcoupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount'), ('product_qty', 'Product Qty')], default='percentage', max_length=20),
        ),
    ]
