# Generated by Django 6.0.6 on 2026-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productcoupon_min_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcoupon',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat Amount'), ('product_qty', 'Product Qty')], default='flat', max_length=20),
        ),
    ]
