# Generated by Django 6.0.6 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
