# Generated by Django 6.0.6 on 2026-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updationtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Updated', 'Updated'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
