# Generated by Django 6.0.6 on 2026-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_updationtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='updationtask',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High Priority'), ('Low', 'Low Priority')], max_length=10, null=True),
        ),
    ]
