# Generated by Django 6.0.6 on 2026-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_updationtask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updationtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Updated', 'Updated'), ('Completed', 'Completed'), ('Invalid', 'Invalid')], default='Pending', max_length=20),
        ),
    ]
