# Generated by Django 6.0.6 on 2026-08-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='place',
        ),
    ]
