# Generated by Django 6.0.6 on 2026-08-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_order_coupon_code_order_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('house_flat_number', models.CharField(max_length=255)),
                ('street_area', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='product.siteuser')),
            ],
            options={
                'verbose_name': 'Saved Address',
                'verbose_name_plural': 'Saved Addresses',
                'db_table': 'saved_addresses',
                'ordering': ['created_at'],
            },
        ),
    ]
