# Generated by Django 6.0.6 on 2026-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
