# Generated by Django 6.0.6 on 2026-08-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_savedaddress_email_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
