# Generated by Django 6.0.6 on 2026-08-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='updationtask',
            name='related_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='updation_images/'),
        ),
    ]
