# Generated by Django 6.0.6 on 2026-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_content', models.CharField(blank=True, default='', max_length=255)),
                ('hero_para_1', models.TextField(blank=True, default='')),
                ('hero_para_2', models.TextField(blank=True, default='')),
                ('hero_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='hero_section/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'db_table': 'hero_section',
            },
        ),
    ]
