# Generated by Django 6.0.6 on 2026-08-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='hero_section/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.herosection')),
            ],
            options={
                'db_table': 'hero_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
