# Generated by Django 6.0.6 on 2026-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='marquee_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
