# Generated by Django 6.0.6 on 2026-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_herosection_marquee_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fake_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
