# Generated by Django 6.0.6 on 2026-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_product_fake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='toggle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
