# Generated by Django 6.0.6 on 2026-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_herosection_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='toggle_para',
            field=models.TextField(blank=True, default=''),
        ),
    ]
