# Generated by Django 6.0.6 on 2026-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_herosection_toggle_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_toggle_page',
            field=models.BooleanField(default=False),
        ),
    ]
