# Generated by Django 6.0.6 on 2026-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_product_show_on_toggle_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Admin', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Admin Auth',
                'verbose_name_plural': 'Admin Auth',
                'db_table': 'admin_auth',
            },
        ),
    ]
