from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/products/', views.list_products, name='list_products'),
    path('admin-panel/products/add/', views.add_product, name='add_product'),
    path('admin-panel/products/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('admin-panel/products/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('admin-panel/products/update-categories/<int:pk>/', views.update_product_categories, name='update_product_categories'),
    path('admin-panel/product-images/delete/<int:pk>/', views.delete_product_image, name='delete_product_image'),
    path('admin-panel/categories/', views.list_categories, name='list_categories'),
    path('admin-panel/categories/add/', views.add_category, name='add_category'),
    path('admin-panel/categories/edit/<int:pk>/', views.edit_category, name='edit_category'),
    path('admin-panel/categories/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('explore-onam/', views.onam_saree_explore, name='onam_saree_explore'),
    path('explore-colored-sarees/', views.colored_saree_explore, name='colored_saree_explore'),
    path('explore-onam-mund/', views.onam_mund_explore, name='onam_mund_explore'),
    path('modal/<str:product_type>/<int:pk>/', views.product_modal, name='product_modal'),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('admin-panel/users/', views.list_users, name='list_users'),
    path('admin-panel/users/edit/<int:pk>/', views.edit_user, name='edit_user'),
    path('admin-panel/users/delete/<int:pk>/', views.delete_user, name='delete_user'),
    path('admin-panel/user-data/', views.list_user_data, name='list_user_data'),
    path('admin-panel/user-data/download-csv/', views.download_user_data_csv, name='download_user_data_csv'),
    path('admin-panel/updations/', views.manage_updations, name='manage_updations'),
    path('admin-panel/updations/add/', views.add_updation, name='add_updation'),
    path('admin-panel/manual-selling/', views.manual_selling, name='manual_selling'),
    path('admin-panel/updations/status/<int:pk>/', views.update_updation_status, name='update_updation_status'),
    path('admin-panel/delivered-orders/', views.list_delivered_orders, name='list_delivered_orders'),
    path('admin-panel/update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('admin-panel/order/delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-success/', views.order_success, name='order_success'),
    path('my-orders/', views.my_orders, name='my_orders'),
]
